baseURL = "https://jmvb.xyz/"
languageCode = "en-us"
title = "jmvb.xyz"

theme = "cactus"

[params]
  colortheme = "white" 
  css = ["css/custom.css"]
  description = """
  In this blog, I embark on a quest to unravel the complexities 
  I once struggled to comprehend. By writing about these subjects, 
  I am compelled to confront challenging questions head-on. 
  This process helps alleviate the cognitive load, enabling me to construct 
  a clearer mental model. Articulating my understanding to an anonymous 
  reader allows me to gain a broader perspective, revealing the bigger picture. 
  """
  mainSection = "posts"
  howAllPostsOnHomePage = true
  rss = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[params.social]]
  name = "github"
  link = "https://github.com/jeremybaumont"

[[params.social]]
  name = "email"
  link = "i9ijfmq6k@mozmail.com"

[[params.social]]
  name = "mastodon"
  link = "https://hachyderm.io/@rodeeend"
